import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/Navbar";
import Footer from "./ui/Footer";
import { NavDesktop } from "./ui/NavDesktop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="grid grid-rows-[60px_1fr_60px]">
          <NavBar />

          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
